# Automatically generated by configure - do not modify
SRC_PATH=/home/dinuni_local/postcopy/latest/qemu-2.8.1.1_modified/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
